version: "3.4"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbvolume:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisvolume:/data

  backend:
    build: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: frontend
    stdin_open: true
    ports:
      - 80:3000
    volumes:
      - ./frontend:/usr/src/app

volumes:
  mongodbvolume:
  redisvolume:
  